version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: ["npm", "start"]
    depends_on:
      - backend
